### ISSUE TITLE
[FEAT] 회원 조회 기능 개발

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/order-service#4]
## 📝 이슈 내용
회원 조회 기능 개발

## 📝 상세 내용
회원 레포지토리 내용 추가
회원 조회 서비스 개발
회원 조회 테스트 코드 작성

## ✅ TODO
- [x] 회원 레포지토리 내용 추가
- [x] 회원 조회 서비스 개발
- [x] 회원 조회 테스트 코드 작성
