### ISSUE TITLE
[FEAT] 상품 조회 기능 개발

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/order-service#7]
## 📝 이슈 내용
상품 조회 개발

## 📝 상세 내용
상품 조회 레포지토리 추가
상품 조회 서비스 개발
상품 조회 테스트 코드 작성

## ✅ TODO
- [x] 상품 조회 레포지토리 추가
- [x] 상품 조회 서비스 개발
- [x] 상품 조회 테스트 코드 작성
