### ISSUE TITLE
[FEAT] 주문 등록 기능 개발

### ISSUE THREAD

**Issue by ehBeak** [ehBeak/order-service#8]
## 📝 이슈 내용
주문 등록 기능 개발

## 📝 상세 내용
주문 레포지토리 추가
주문 등록 서비스 개발
주문 등록 테스트 코드 작성

## ✅ TODO
- [x] 주문 레포지토리 추가
- [x] 주문 등록 서비스 개발
- [x] 주문 등록 테스트 코드 작성
